version: '3'

services:
  fastapi:
    build: fastApi/
    ports:
      - 8000:8000
    networks:
      - deploy_network
    #command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: fastApi

  streamlit:
    build: streamlit/
    depends_on:
      - fastApi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    #command: streamlit run app.py
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge