name: test du compose
on: {} # set the events you would like to trigger this job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: farid.ahamada25@gmail.com # your heroku email
          api_key: b4e08674-eaf0-4270-885c-77629bd10d65 # your  heroku api key
          docker_compose_file: 'docker-compose.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"fastApi","appname":"honchoappgender","apptype":"web"},{"imagename":"streamlit","appname":"honchoappgender","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type